export const icons = {
  discoverActive: require("../assets/images/icons/discover-active.svg"),
  discover: require("../assets/images/icons/discover.svg"),
  more: require("../assets/images/icons/more.svg"),
  moreActive: require("../assets/images/icons/more-active.svg"),
  bookActive: require("../assets/images/icons/book-active.svg"),
  book: require("../assets/images/icons/book.svg"),
  arrowLeft: require("../assets/images/icons/arrow-left.svg"),
  arrowRight: require("../assets/images/icons/arrow-right.svg"),
  arrowDown: require("../assets/images/icons/arrow-down.svg"),
  backward: require("../assets/images/icons/backward.svg"),
  forward: require("../assets/images/icons/forward.svg"),
  close: require("../assets/images/icons/close.svg"),
  checkmark: require("../assets/images/icons/checkmark.svg"),
  brush: require("../assets/images/icons/brush.svg"),
  share: require("../assets/images/icons/share.svg"),
  volume: require("../assets/images/icons/volume.svg"),
  ranking: require("../assets/images/icons/ranking.svg"),
  play: require("../assets/images/icons/play.svg"),
  pause: require("../assets/images/icons/pause.svg"),
  search: require("../assets/images/icons/search.svg"),
};
